Add timezone grid caching to CLI (#17)
bellingcat/ShadowFinder pull request #21
Opened 2024-07-22 17:25 UTC by borisnezlobin

I've gone ahead and implemented the changes described in [Galen's comment](https://github.com/bellingcat/ShadowFinder/issues/17#issuecomment-2242439921). The only notable change in behaviour is that now, by default, `find_sun` and `find` will attempt to read from `timezone_grid.json` (even if no `--grid` argument is passed). If this is unwanted, I can change it back, I just thought it would be a good default.

While testing, I found that `finder.generate_timezone_grid()` generates a JSON file that doesn't match the `timezone_grid.json` currently in this repo... is that intentional? Also, `shadowfinder generate_timezone_grid` will overwrite the file it's given — should that be changed?

2024-07-23 11:51 UTC, GalenReich commented
> finder.generate_timezone_grid() generates a JSON file that doesn't match the timezone_grid.json currently in this repo

This isn't intentional, and is probably not desired either! The behaviour is controlled by these defaults: https://github.com/bellingcat/ShadowFinder/blob/e5f636b3f4496ffd77cdc597380d3a531b71f019/src/shadowfinder/shadowfinder.py#L36-L40

It would be good to understand why this is happening

2024-07-23 16:56 UTC, borisnezlobin commented
I've just checked a lot more thoroughly (before, I was just looking at files changed, now I ran it through diffchecker.com) — the only difference is a trailing newline is removed. Sorry about that! I've also updated the tests so the reflect the new output.

2024-07-25 10:27 UTC, GalenReich requested changes
In general it looks good!

One small thing, `find_sun` needs updating to include the grid argument.

2024-07-25 10:28 UTC, GalenReich commented
> I've just checked a lot more thoroughly (before, I was just looking at files changed, now I ran it through diffchecker.com) — the only difference is a trailing newline is removed. Sorry about that! I've also updated the tests so the reflect the new output.

No worries at all, better for it to be a newline than an entirely different set of points! So thank you for noticing the difference and double checking!

2024-07-25 17:46 UTC, borisnezlobin commented
> One small thing, find_sun needs updating to include the grid argument.

...oops. I've fixed it now, I think. Would it be a good idea to add the modified `timezone_grid.json` to Git (and, I think, disable the pre-commit formatting for it)?

2024-08-24 18:24 UTC, borisnezlobin commented
bump. Anything else that needs to be fixed?

2024-08-28 10:14 UTC, GalenReich approved these changes

2024-08-28 10:14 UTC, GalenReich commented
This all looks good - apologies about the delay, and thanks for the bump! 🙌

2024-08-28 10:27 UTC, merged